name: SupaStorage-backup
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:
    schedule:
        - cron: '0 8,20 * * *'

    jobs:
        backup:
            runs-on: ubuntu-latest
            env:
                SUPABASE_URL: https://qwbufbmxkjfaikoloudl.supabase.co
                SUPABASE_SERVICE_ROLE: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3YnVmYm14a2pmYWlrb2xvdWRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE2Njk5NDE3NTksImV4cCI6MTk4NTUxNzc1OX0.RNz5bvsVwLvfYpZtUjy0vBPcho53_VS2AIVzT8Fm-lk
            permissions:
                contents: write
            steps:
                - name: Checkout code
                  uses: actions/checkout@v3
                  with:
                    ref: ${{ gtihub.head_ref }}
                - name: Set up Python
                  uses: actions/setup-python@v4
                  with:
                    python-version: '3.10'
                
                - name: Install dependencies and perform backup
                  run: |
                    pip install supabase
                    [[ -d supabase_storage_backup ]] | mkdir supabase_storage_backup
                    cd supabase_storage_backup
                    wget https://raw.githubusercontent.com/signal-k/client/main/storage-backup.py
                    chmod +x storage-backup.py
                    python storage-backup.py
                    rm storage-backup.py
                shell: bash

            - name: Set current date as env variable
              run: echo "NOW=$(date + '%Y -%m-%dT%H:%M:%S')" >> $GITHUB_ENV
            - uses: 